server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${MCAFE_DB_URL}
    username: ${MCAFE_DB_USERNAME}
    password: ${MCAFE_DB_PASSWORD}
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      max-lifetime: 120000
      maximum-pool-size: 4
  data:
    redis:
      host: ${MCAFE_REDIS_HOST}
      port: ${MCAFE_REDIS_PORT}
      username: ${MCAFE_REDIS_USERNAME}
      password: ${MCAFE_REDIS_PASSWORD}

  mvc:
    path match:
      matching-strategy: ant_path_matcher

web-client:
  connect-timeout: 5000
  read-timeout: 10000
  write-timeout: 10000

u-chef:
  shop-member-seq: 1859
  domain: https://uchef.co.kr/
  path:
    project-seq: /webApp.action?shop_member_seq={shop_member_seq}&mode=5150
    security-id: /webApp.action?mode=7100&shop_member_seq={shop_member_seq}&phone_id={phone}&project_seq={project_seq}
    login: /webApp.action?mode=7100&shop_member_seq={shop_member_seq}&phone_id={phone}&passwd={password}&project_seq={project_seq}
    menu: /webApp.action?mode=5151&shop_member_seq={shop_member_seq}&project_seq={project_seq}
    menu-info: /webApp.action?mode=5170&item_code={menu_code}&shop_member_seq={shop_member_seq}
    pay-order: /webApp.action?mode=5060&table_name=TKO&order_list={order_list}&ordered_cnt=0&cs_name={cs_name}&phone={phone}&is_pre_pay=0&coupon_id=welfare%20discount&coupon_amount={coupon_amount}&point_amount=0&pay_tip=0&shop_member_seq={shop_member_seq}&project_seq={project_seq}

jwt:
  secret:
    key: ENC(wo85QhTHIrilTgPhSHmBKg==)
  access:
    token:
      expiration: 240
  refresh:
    token:
      expiration: 240