server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${MCAFE_DB_URL}
    username: ${MCAFE_DB_USERNAME}
    password: ${MCAFE_DB_PASSWORD}
  mvc:
    path match:
      matching-strategy: ant_path_matcher

web-client:
  connect-timeout: 5000
  read-timeout: 10000
  write-timeout: 10000

u-chef:
  shop-member-seq: 1859
  domain: https://uchef.co.kr/
  path:
    project-seq: /webApp.action?shop_member_seq={shop_member_seq}&mode=5150
    menu: /webApp.action?mode=5151&shop_member_seq={shop_member_seq}&project_seq={project_seq}
    menu-info: /webApp.action?mode=5170&item_code={menu_code}&shop_member_seq={shop_member_seq}

jwt:
  secret:
    key: ENC(wo85QhTHIrilTgPhSHmBKg==)
  access:
    token:
      expiration: 30
  refresh:
    token:
      expiration: 30